name: Set latest
on:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [main]
jobs:
  set-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: get most recent git tag
        run: |
          newestTag=git tag -l --sort=-v:taggerdate | tail -1
          echo 'NEWEST_TAG='$newestTag >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: set latest tag to most recent tag
        run: |
          gh release edit $NEWEST_TAG --target=main --latest=true --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          